from __future__ import annotations

import json
from pathlib import Path
from typing import Any


_FAMILY_MACRO_SUFFIX = {
    "hot_column_rename": "Rename",
    "add_non_null_column": "AddNN",
    "type_narrowing": "TypeNarrow",
    "drop_legacy_column": "DropLegacy",
    "add_foreign_key": "AddFK",
}


def _fmt_num(value: float | int | None, digits: int = 1) -> str:
    if value is None:
        return ".."
    if isinstance(value, int):
        return str(value)
    return f"{value:.{digits}f}"


def _pct(value: float | None) -> str:
    if value is None:
        return ".."
    return f"{value:.1f}\\%"


def _family_counts(
    summary: dict[str, Any], family: str, strategy: str
) -> tuple[int, int, int]:
    fam = summary.get("families", {}).get(family, {}).get(strategy, {})
    success = int(fam.get("success", 0))
    failure = int(fam.get("failure", 0))
    denominator = int(fam.get("completed_pairs", fam.get("scenario_pairs", success + failure)))
    return success, failure, denominator


def generate_results_tex(summary: dict[str, Any]) -> str:
    pg_version = str(summary.get("pg_version", "16.3"))
    suite_size = int(summary.get("suite_size", 0))
    repetitions = int(summary.get("repetitions_per_scenario_strategy", 1))

    strategies = summary.get("strategies", {})
    a = strategies.get("baseline_a", {})
    b = strategies.get("baseline_b", {})

    a_safe = int(a.get("safe_success", 0))
    b_safe = int(b.get("safe_success", 0))

    lines = [
        "% Auto-generated by pgmigbench report",
        f"\\providecommand{{\\PGVersion}}{{PostgreSQL~{pg_version}}}",
        f"\\providecommand{{\\SuiteSize}}{{{suite_size}}}",
        f"\\providecommand{{\\BenchmarkRepetitions}}{{{repetitions}}}",
        "",
        f"\\providecommand{{\\A_Safe}}{{{a_safe}/{suite_size}}}",
        f"\\providecommand{{\\A_SafePct}}{{{a.get('safe_success_pct', '0.0%').replace('%', '\\%')}}}",
        f"\\providecommand{{\\A_SafeCI}}{{{a.get('safe_success_ci_95', '[0.0%, 0.0%]').replace('%', '\\%')}}}",
        f"\\providecommand{{\\A_LockViol}}{{{int(a.get('lock_violations', 0))}}}",
        f"\\providecommand{{\\A_UnsafeDestructive}}{{{int(a.get('unsafe_destructive_actions', a.get('data_loss_incidents', 0)))}}}",
        f"\\providecommand{{\\A_CompatBreak}}{{{int(a.get('compat_breaks', 0))}}}",
        "",
        f"\\providecommand{{\\B_Safe}}{{{b_safe}/{suite_size}}}",
        f"\\providecommand{{\\B_SafePct}}{{{b.get('safe_success_pct', '0.0%').replace('%', '\\%')}}}",
        f"\\providecommand{{\\B_SafeCI}}{{{b.get('safe_success_ci_95', '[0.0%, 0.0%]').replace('%', '\\%')}}}",
        f"\\providecommand{{\\B_LockViol}}{{{int(b.get('lock_violations', 0))}}}",
        f"\\providecommand{{\\B_UnsafeDestructive}}{{{int(b.get('unsafe_destructive_actions', b.get('data_loss_incidents', 0)))}}}",
        f"\\providecommand{{\\B_CompatBreak}}{{{int(b.get('compat_breaks', 0))}}}",
        "",
        f"\\providecommand{{\\A_PeakLockP95}}{{{_fmt_num(a.get('ops', {}).get('peak_lock_wait_ms_p95'), 1)}}}",
        f"\\providecommand{{\\B_PeakLockP95}}{{{_fmt_num(b.get('ops', {}).get('peak_lock_wait_ms_p95'), 1)}}}",
        f"\\providecommand{{\\A_P95LatDelta}}{{{_pct(a.get('ops', {}).get('latency_delta_pct_p95'))}}}",
        f"\\providecommand{{\\B_P95LatDelta}}{{{_pct(b.get('ops', {}).get('latency_delta_pct_p95'))}}}",
        f"\\providecommand{{\\A_DurationMed}}{{{_fmt_num(a.get('ops', {}).get('duration_s_median'), 1)}s}}",
        f"\\providecommand{{\\B_DurationMed}}{{{_fmt_num(b.get('ops', {}).get('duration_s_median'), 1)}s}}",
        "",
    ]

    # Optional per-family macros for article tables.
    lines.append("% Per-family breakdown macros")
    for family, suffix in _FAMILY_MACRO_SUFFIX.items():
        a_success, a_failure, a_denominator = _family_counts(summary, family, "baseline_a")
        b_success, b_failure, b_denominator = _family_counts(summary, family, "baseline_b")
        lines.append(f"\\providecommand{{\\A_{suffix}Success}}{{{a_success}/{a_denominator}}}")
        lines.append(f"\\providecommand{{\\A_{suffix}Fail}}{{{a_failure}}}")
        lines.append(f"\\providecommand{{\\B_{suffix}Success}}{{{b_success}/{b_denominator}}}")
        lines.append(f"\\providecommand{{\\B_{suffix}Fail}}{{{b_failure}}}")
    lines.append("")
    return "\n".join(lines)


def write_results_tex(summary: dict[str, Any], out_path: Path) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(generate_results_tex(summary), encoding="utf-8")


def load_summary(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))
