from pgmigbench.report.aggregate import aggregate_rows


def test_aggregate_builds_strategy_and_family_totals() -> None:
    rows = [
        {
            "run_id": "r1",
            "repeat_index": 1,
            "scenario_id": "s1",
            "family": "add_non_null_column",
            "strategy": "baseline_a",
            "variant": "v1",
            "rows": 100000,
            "workload_level": "low",
            "success": True,
            "lock_violations": 0,
            "unsafe_destructive_actions": 0,
            "postcheck_failures": 0,
            "compat_breaks": 0,
            "peak_blocked_backends": 0,
            "peak_lock_wait_ms": 10.0,
            "baseline_latency_ms": 1.0,
            "mig_latency_ms": 1.2,
            "latency_delta_pct": 20.0,
            "duration_s": 5.0,
            "pg_version": "16.3",
            "seed": 2026,
            "started_at_utc": "2026-01-01T00:00:00+00:00",
            "error": "",
        },
        {
            "run_id": "r1",
            "repeat_index": 2,
            "scenario_id": "s1",
            "family": "add_non_null_column",
            "strategy": "baseline_a",
            "variant": "v1",
            "rows": 100000,
            "workload_level": "low",
            "success": True,
            "lock_violations": 0,
            "unsafe_destructive_actions": 0,
            "postcheck_failures": 0,
            "compat_breaks": 0,
            "peak_blocked_backends": 0,
            "peak_lock_wait_ms": 12.0,
            "baseline_latency_ms": 1.0,
            "mig_latency_ms": 1.3,
            "latency_delta_pct": 30.0,
            "duration_s": 5.5,
            "pg_version": "16.3",
            "seed": 2026,
            "started_at_utc": "2026-01-01T00:00:00+00:00",
            "error": "",
        },
        {
            "run_id": "r1",
            "repeat_index": 1,
            "scenario_id": "s1",
            "family": "add_non_null_column",
            "strategy": "baseline_b",
            "variant": "v1",
            "rows": 100000,
            "workload_level": "low",
            "success": False,
            "lock_violations": 1,
            "unsafe_destructive_actions": 0,
            "postcheck_failures": 0,
            "compat_breaks": 1,
            "peak_blocked_backends": 4,
            "peak_lock_wait_ms": 25.0,
            "baseline_latency_ms": 1.0,
            "mig_latency_ms": 1.5,
            "latency_delta_pct": 50.0,
            "duration_s": 7.0,
            "pg_version": "16.3",
            "seed": 2026,
            "started_at_utc": "2026-01-01T00:00:00+00:00",
            "error": "deadlock detected",
        },
        {
            "run_id": "r1",
            "repeat_index": 2,
            "scenario_id": "s1",
            "family": "add_non_null_column",
            "strategy": "baseline_b",
            "variant": "v1",
            "rows": 100000,
            "workload_level": "low",
            "success": True,
            "lock_violations": 0,
            "unsafe_destructive_actions": 0,
            "postcheck_failures": 0,
            "compat_breaks": 0,
            "peak_blocked_backends": 0,
            "peak_lock_wait_ms": 18.0,
            "baseline_latency_ms": 1.0,
            "mig_latency_ms": 1.1,
            "latency_delta_pct": 10.0,
            "duration_s": 6.0,
            "pg_version": "16.3",
            "seed": 2026,
            "started_at_utc": "2026-01-01T00:00:00+00:00",
            "error": "",
        },
    ]

    summary = aggregate_rows(
        rows,
        suite_size=1,
        repetitions=2,
        seed=2026,
        pg_version="16.3",
        started_at_utc="2026-01-01T00:00:00+00:00",
        finished_at_utc="2026-01-01T00:01:00+00:00",
    )

    assert summary["strategies"]["baseline_a"]["safe_success"] == 1
    assert summary["strategies"]["baseline_b"]["safe_success"] == 0
    assert summary["strategies"]["baseline_b"]["lock_violations"] == 1
    assert summary["strategies"]["baseline_a"]["runs"] == 2
    assert summary["strategies"]["baseline_b"]["scenario_pairs_completed"] == 1
    assert summary["families"]["add_non_null_column"]["baseline_a"]["success"] == 1
    assert summary["families"]["add_non_null_column"]["baseline_b"]["failure"] == 1
